### PR TITLE
Improve README.md - Add blockchain section / fix typos

### PR DESCRIPTION
**Pull request by beckettnormington**
README with added blockchain info - I was unable to add an installation section. My second official PR on Github. Best wishes - Beckett

### CODE REVIEW

**Comment by beckettnormington** [comment]
If you would like to support me, you can add the "hacktoberfest-accepted" label to this PR, so that I get credited for this PR. Have a great day! -Beckett

**Comment by annu12340** [comment]
e

> README with added blockchain info - **I was unable to add an installation section**. My second official PR on Github. Best wishes - Beckett

Hey @beckettnormington, could you tell what was the difficulty that you faced during installation

**Review by annu12340 — CHANGES_REQUESTED** [review]
The content looks good 😄 
Could you add more one heading on how bc can impact elections

**Comment by beckettnormington** [comment]
My installation got dismantled by my antivirus. Exclusion settings did nothing, only stopped the alerts. I'll add that section right now!

**Comment by beckettnormington** [comment]
Section updated!

**Review by annu12340 — APPROVED** [review]

**Comment by annu12340** [comment]
Thanks for the pr :)

**Comment by beckettnormington** [comment]
You're welcome! Thanks!

**Pull request merged**
